/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ocl_rpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
ocl_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		plat_id_t get_plat_id_1_arg;
		plat_info_t get_plat_info_1_arg;
		get_devs_t get_devs_id_1_arg;
		create_ctx_t create_ctx_1_arg;
		create_cqueue_t create_cqueue_1_arg;
		create_prog_ws_t create_prog_ws_1_arg;
		build_prog_t build_prog_1_arg;
		create_kern_t create_kern_1_arg;
		create_buf_t create_buf_1_arg;
		set_kern_arg_t set_kern_arg_1_arg;
		enq_ndr_kern_t enq_ndr_kern_1_arg;
		finish_t finish_1_arg;
        enq_map_buf_t enq_map_buf_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GET_PLAT_ID:
		_xdr_argument = (xdrproc_t) xdr_plat_id_t;
		_xdr_result = (xdrproc_t) xdr_plat_id_t;
		local = (char *(*)(char *, struct svc_req *)) get_plat_id_1_svc;
		break;

	case GET_PLAT_INFO:
		_xdr_argument = (xdrproc_t) xdr_plat_info_t;
		_xdr_result = (xdrproc_t) xdr_plat_info_t;
		local = (char *(*)(char *, struct svc_req *)) get_plat_info_1_svc;
		break;

	case GET_DEVS_ID:
		_xdr_argument = (xdrproc_t) xdr_get_devs_t;
		_xdr_result = (xdrproc_t) xdr_get_devs_t;
		local = (char *(*)(char *, struct svc_req *)) get_devs_id_1_svc;
		break;

	case CREATE_CTX:
		_xdr_argument = (xdrproc_t) xdr_create_ctx_t;
		_xdr_result = (xdrproc_t) xdr_create_ctx_t;
		local = (char *(*)(char *, struct svc_req *)) create_ctx_1_svc;
		break;

	case CREATE_CQUEUE:
		_xdr_argument = (xdrproc_t) xdr_create_cqueue_t;
		_xdr_result = (xdrproc_t) xdr_create_cqueue_t;
		local = (char *(*)(char *, struct svc_req *)) create_cqueue_1_svc;
		break;

	case CREATE_PROG_WS:
		_xdr_argument = (xdrproc_t) xdr_create_prog_ws_t;
		_xdr_result = (xdrproc_t) xdr_create_prog_ws_t;
		local = (char *(*)(char *, struct svc_req *)) create_prog_ws_1_svc;
		break;

	case BUILD_PROG:
		_xdr_argument = (xdrproc_t) xdr_build_prog_t;
		_xdr_result = (xdrproc_t) xdr_build_prog_t;
		local = (char *(*)(char *, struct svc_req *)) build_prog_1_svc;
		break;

	case CREATE_KERN:
		_xdr_argument = (xdrproc_t) xdr_create_kern_t;
		_xdr_result = (xdrproc_t) xdr_create_kern_t;
		local = (char *(*)(char *, struct svc_req *)) create_kern_1_svc;
		break;

	case CREATE_BUF:
		_xdr_argument = (xdrproc_t) xdr_create_buf_t;
		_xdr_result = (xdrproc_t) xdr_create_buf_t;
		local = (char *(*)(char *, struct svc_req *)) create_buf_1_svc;
		break;

	case SET_KERN_ARG:
		_xdr_argument = (xdrproc_t) xdr_set_kern_arg_t;
		_xdr_result = (xdrproc_t) xdr_set_kern_arg_t;
		local = (char *(*)(char *, struct svc_req *)) set_kern_arg_1_svc;
		break;

	case ENQ_NDR_KERN:
		_xdr_argument = (xdrproc_t) xdr_enq_ndr_kern_t;
		_xdr_result = (xdrproc_t) xdr_enq_ndr_kern_t;
		local = (char *(*)(char *, struct svc_req *)) enq_ndr_kern_1_svc;
		break;

	case FINISH:
		_xdr_argument = (xdrproc_t) xdr_finish_t;
		_xdr_result = (xdrproc_t) xdr_finish_t;
		local = (char *(*)(char *, struct svc_req *)) finish_1_svc;
		break;

	case ENQ_MAP_BUF:
		_xdr_argument = (xdrproc_t) xdr_enq_map_buf_t;
		_xdr_result = (xdrproc_t) xdr_enq_map_buf_t;
		local = (char *(*)(char *, struct svc_req *)) enq_map_buf_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (OCL_PROG, OCL_VERS);

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, OCL_PROG, OCL_VERS, ocl_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (OCL_PROG, OCL_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
